name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node.js (for backend + frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies for backend microservices
      - name: Install backend dependencies
        run: |
          cd backend/api-gateway && npm install && cd -
          cd backend/auth-service && npm install && cd -
          cd backend/patient-service && npm install && cd -
          cd backend/prescription-service && npm install && cd -
          cd backend/profile-control-service && npm install && cd -

      # Install dependencies for frontend
      - name: Install frontend dependencies
        run: |
          cd frontend && npm install && cd -

      # Start backend services one by one
      - name: Start all backend services
        run: |
          nohup node backend/auth-service/src/server.js > backend/auth-service/auth.log 2>&1 &
          nohup node backend/patient-service/src/server.js > backend/patient-service/patient.log 2>&1 &
          nohup node backend/prescription-service/src/server.js > backend/prescription-service/prescription.log 2>&1 &
          nohup node backend/profile-control-service/src/server.js > backend/profile-control-service/profile.log 2>&1 &
          nohup node backend/api-gateway/src/server.js > backend/api-gateway/gateway.log 2>&1 &
          sleep 30  # wait for all services to be ready

      # Start frontend service
      - name: Start Frontend
        run: |
          cd frontend
          # Make log file in current folder
          nohup npm run dev -- --host 0.0.0.0 > frontend.log 2>&1 &
          cd ..
          sleep 20

      # # Health checks for backend + frontend
      # - name: Check API Gateway
      #   run: curl -f http://localhost:4000

      # - name: Check Auth Service
      #   run: curl -f http://localhost:5001

      # - name: Check Patient Service
      #   run: curl -f http://localhost:5000

      # - name: Check Prescription Service
      #   run: curl -f http://localhost:5004

      # - name: Check Profile Control Service
      #   run: curl -f http://localhost:5008

      # - name: Check Frontend
      #   run: curl -f http://localhost:5173

      # Health checks for backend + frontend using nc
      - name: Check API Gateway
        run: nc -zv localhost 4000

      - name: Check Auth Service
        run: nc -zv localhost 5001

      - name: Check Patient Service
        run: nc -zv localhost 5000

      - name: Check Prescription Service
        run: nc -zv localhost 5004

      - name: Check Profile Control Service
        run: nc -zv localhost 5008

      - name: Check Frontend
        run: nc -zv localhost 5173